"""Updated user model

Revision ID: 8e17c8cc8734
Revises: aca84bd22911
Create Date: 2025-12-09 23:35:29.446615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8e17c8cc8734'
down_revision: Union[str, Sequence[str], None] = 'aca84bd22911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
