"""Added new fields to randomitem

Revision ID: bdc49820fff4
Revises: 4f732db560c8
Create Date: 2025-11-15 15:24:59.164254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc49820fff4'
down_revision: Union[str, Sequence[str], None] = '4f732db560c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('randomitem', sa.Column('min_value', sa.Integer(), nullable=False))
    op.add_column('randomitem', sa.Column('max_value', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('randomitem', 'max_value')
    op.drop_column('randomitem', 'min_value')
    # ### end Alembic commands ###
